[package]
name = "orb"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
imageproc = "0.25.0"
num_cpus = "1.17.0"
rayon = "1.10.0"

[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
rustflags = [
  "-Ctarget-cpu=native",
  "-Ctarget-feature=+neon"
]
