[workspace]
members = [
    "orb-core",
    "orb-fast", 
    "orb-brief",
    "orb-cli"
]
resolver = "2"

[workspace.dependencies]
image = "0.25.6"
imageproc = "0.25.0"
num_cpus = "1.17.0"
rayon = "1.10.0"
