width = 512
height = 512
enable_simd = true
enable_optimized_layout = true
enable_harris_corners = false
enable_adaptive_thresholding = false
enable_clahe_preprocessing = false
nms_distance = 3.0
subpixel_refinement = false
name = "Production Fast"
description = "Optimized for real-time applications"
version = "1.0.0"

[core]
threshold = 25
patch_size = 15
n_threads = 1
