width = 512
height = 512
enable_simd = true
enable_optimized_layout = true
enable_harris_corners = true
enable_adaptive_thresholding = true
enable_clahe_preprocessing = true
nms_distance = 5.0
subpixel_refinement = true
name = "Research Quality"
description = "Maximum feature detection quality"
version = "1.0.0"

[core]
threshold = 20
patch_size = 15
n_threads = 1
