width = 567
height = 567
enable_simd = true
enable_optimized_layout = true
enable_harris_corners = true
enable_adaptive_thresholding = true
enable_clahe_preprocessing = false
nms_distance = 2.5
subpixel_refinement = true
name = "Research Quality"
description = "Maximum feature detection quality"
version = "1.0"

[core]
threshold = 15
patch_size = 23
n_threads = 20
nms_radius = 2.5

[core.fast_variant]
FastN = 10
